import Head from 'next/head'
import { useState } from 'react'
import KanaCard from './KanaCard'
import ErrorList from './ErrorList'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [round, setRound] = useState(0)
  return (
    <div className={styles.container}>
      <Head>
        <title>Kana School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <KanaCard round={round} onRoundEnd={() => setRound(round + 1)} />
        <ErrorList round={round} />
      </main>
    </div>
  )
}
